=== jhu-bigss/grbl_ros2_gui/grbl_ros2_gui/i18n/cn5X_locales.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'                                                                         '
' Copyright 2018 Gauthier BriÃ¨re (gauthier.briere "at" gmail.com)         '
'                                                                         '
' This file is part of cn5X++                                               '
'                                                                         '
' cn5X++ is free software: you can redistribute it and/or modify it         '
'  under the terms of the GNU General Public License as published by      '
' the Free Software Foundation, either version 3 of the License, or       '
' (at your option) any later version.                                     '
'                                                                         '
' cn5X++ is distributed in the hope that it will be useful, but           '
' WITHOUT ANY WARRANTY; without even the implied warranty of              '
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the           '
' GNU General Public License for more details.                            '
'                                                                         '
' You should have received a copy of the GNU General Public License       '
' along with this program.  If not, see <http://www.gnu.org/licenses/>.   '
'                                                                         '
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="locales">
    <xs:element name="translation">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="locale" type="xs:string" />
          <xs:element name="label" type="xs:string" />
          <xs:element name="qm_file" type="xs:string" />
          <xs:element name="flag_file" type="xs:string" />
        </xs:sequence>
      </xs:complexType>
    </xs:element>
  </xs:element>
</xs:schema>

=== jhu-bigss/grbl_ros2_gui/grbl_ros2_gui/i18n/cn5X_locales.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'                                                                         '
' Copyright 2018 Gauthier Brière (gauthier.briere "at" gmail.com)         '
'                                                                         '
' This file is part of cn5X++                                               '
'                                                                         '
' cn5X++ is free software: you can redistribute it and/or modify it         '
'  under the terms of the GNU General Public License as published by      '
' the Free Software Foundation, either version 3 of the License, or       '
' (at your option) any later version.                                     '
'                                                                         '
' cn5X++ is distributed in the hope that it will be useful, but           '
' WITHOUT ANY WARRANTY; without even the implied warranty of              '
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the           '
' GNU General Public License for more details.                            '
'                                                                         '
' You should have received a copy of the GNU General Public License       '
' along with this program.  If not, see <http://www.gnu.org/licenses/>.   '
'                                                                         '
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
-->

<locales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cn5X_locales.xsd">
  <translation>
    <locale>fr</locale>
    <label>Français</label>
    <qm_file>cn5X.fr.qm</qm_file>
    <flag_file>:/i18n/i18n/flags/flag_fr.svg</flag_file>
  </translation>
  <translation>
    <locale>en</locale>
    <label>English</label>
    <qm_file>cn5X.en.qm</qm_file>
    <flag_file>:/i18n/i18n/flags/flag_en.svg</flag_file>
  </translation>
  <inactive_translation>
    <locale>es</locale>
    <label>Español</label>
    <qm_file>cn5X.es.qm</qm_file>
    <flag_file>:/i18n/i18n/flags/flag_es.svg</flag_file>
  </inactive_translation>
  <inactive_translation>
    <locale>pt</locale>
    <label>Português</label>
    <qm_file>cn5X.pt.qm</qm_file>
    <flag_file>:/i18n/i18n/flags/flag_pt.svg</flag_file>
  </inactive_translation>
</locales>
